[package]
org = "ballerinax"
name = "ibm.ibmmq"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["ibm-mq"]
repository = "https://github.com/ballerina-platform/module-ballerinax-ibm.ibmmq"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.8.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "ibm.ibmmq-native"
version = "@toml.version@"
path = "../native/build/libs/ibm.ibmmq-native-@project.version@.jar"
